baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, January 31, 2025"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "10:00am – 2:00pm"
          events:
            - type: "other"
              content: "Registration"
              location: "Taubman Entrance"
        - time: "2:00pm – 2:30pm"
          events:
            - type: "other"
              content: "Welcome Coffee"
              location: "Wexner Commons"
        - time: "2:30pm – 3:30pm"
          events:
            - type: "keynote"
              content: "Opening Ceremony and Flagship Session with Mirjana Spoljaric"
              location: "Nye Auditorium"
              keynote: a
        - time: "3:30pm – 4:00pm"
          events:
            - type: "other"
              content: "Break"
              location: "Wexner Commons"
        - time: "4:00pm – 5:15pm"
          events:
            - type: "keynote"
              content: "Flagship Session with Alexander de Croo"
              location: "JFK Jr. Forum"
              keynote: b
            - type: "panel"
              content: "The Power of Art in Uncertain Times"
              location: "Nye Auditorium"
              code: "l"
        - time: "5:15pm – 5:45pm"
          events:
            - type: "other"
              content: "Break"
              location: "Wexner Commons"
        - time: "5:45pm – 6:30pm"
          events:
            - type: "keynote"
              content: "Flagship Session with Benjamin Haddad"
              location: "JFK Jr. Forum"
              keynote: c
            - type: "fireside"
              content: "Fireside Chat with Mirjana Spoljaric (max 30 guests)"
              location: "Wexner 330"
              fireside: a
            - type: "fireside"
              content: "Fireside Chat with Alexander de Croo (max 30 guests)"
              location: "Wexner 434"
              fireside: b
    - name: "Saturday, February 1, 2025"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "8:00am – 9:00am"
          events:
            - type: "other"
              content: "Breakfast"
              location: "Wexner Commons"
        - time: "9:00am - 10:00am"
          events:
            - type: "keynote"
              content: "Flagship Session"
              location: "JFK Jr. Forum"
              keynote: d
            - type: "panel"
              content: "Boosting Europe's Economy"
              location: "Starr Auditorium"
              code: "a"
            - type: "workshop"
              content: "A Career in the European Parliament and External Action Service"
        - time: "10:00am – 10:15am"
          events:
            - type: "other"
              content: "Break"
              location: "Wexner Commons"
        - time: "10:15am - 11:30am"
          events:
            - type: "panel"
              content: "Fortifying Europe's Frontlines: Ukraine and NATO"
              location: "JFK Jr. Forum"
              code: "h"
            - type: "panel"
              content: "Europe's Role in Middle East Peace"
              location: "Starr Auditorium"
              code: "c"
            - type: "workshop"
              content: "The Future of LGBTQI+ Rights in Europe"
        - time: "11:30am – 12:00pm"
          events:
            - type: "other"
              content: "Coffee Break"
              location: "Wexner Commons"
        - time: "12:00pm - 1:15pm"
          events:
            - type: "panel"
              content: "Europe's Role in Global Diplomacy"
              location: "JFK Jr. Forum"
              code: "j"
            - type: "panel"
              content: "Pretense or Promise? Europe's Climate Ambition"
              location: "Starr Auditorium"
              code: "i"
            - type: "panel"
              content: "A European Brand: Architecture, Hospitality, and Entertainment"
              location: "Wexner 330"
              code: "b"
        - time: "1:15pm – 2:15pm"
          events:
            - type: "other"
              content: "Lunch"
              location: "Wexner Commons"
        - time: "2:15pm - 3:30pm"
          events:
            - type: "panel"
              content: "Europe's Energy Trifecta"
              location: "JFK Jr. Forum"
              code: "f"
            - type: "panel"
              content: "The Union under Strain: Democratic Backsliding"
              location: "Starr Auditorium"
              code: "d"
            - type: "fireside"
              content: "Fireside Chat (max 30 guests) with Tanja Miscevic"
              location: "Wexner 434"
              fireside: "c"
        - time: "3:30pm – 4:00pm"
          events:
            - type: "other"
              content: "Break"
              location: "Wexner Commons"
        - time: "4:00pm - 5:15pm"
          events:
            - type: "panel"
              content: "Migration: Shaping Elections and Societies"
              location: "JFK Jr. Forum"
              code: "e"
            - type: "panel"
              content: "Brain Drain and Emerging Tech"
              location: "Starr Auditorium"
              code: "g"
            - type: "panel"
              content: "The Fight for Human Rights"
              location: "Wexner 330"
              code: "k"
        - time: "5:15pm – 5:30pm"
          events:
            - type: "other"
              content: "Break"
        - time: "5:30pm – 6:30pm"
          events:
            - type: "other"
              content: "Closing Ceremony"
              location: "JFK Jr. Forum"
        - time: "8:00pm - 11:30pm"
          events:
            - type: "other"
              content: "Closing Gala"
              location: "Harvard Art Museum"
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers + Panels
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: Gala
      url: /gala
      pageRef: /Gala
      weight: 35
#    - name: Info
#      url: /info
#      pageRef: /info
#      weight: 40
    - name: About Us
      url: /about-us
      pageRef: /About Us
      weight: 50
    - name: Past Conferences
      weight: 60
    - name: 2024 Conference
      parent: Past Conferences
      rel: external
      url: https://y24.euroconf.eu/
      weight: 10
    - name: 2023 Conference
      parent: Past Conferences
      rel: external
      url: https://y23.euroconf.eu/
      weight: 20
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      weight: 15
    - name: Privacy
      url: /privacy
      weight: 20
    - name: Terms
      url: /terms
      weight: 30
