baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, February 9, 2024"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "11:15am – 12:00pm"
          events:
            - type: "other"
              content: "Registration and Welcome Lunch"
        - time: "12:00pm – 12:45pm"
          events:
            - type: "keynote"
              location: "Nye Auditorium"
              speakers:
                - "gentiloni"
        - time: "12:50pm – 1:50pm"
          events:
            - type: "panel"
              content: "Building Global Coalitions on Feminism, LGBTQ Rights, and Minorities Representation"
              location: "Bell Hall"
              code: "dc"
            - type: "panel"
              content: "Navigating New Normals: Europe’s Economic Resilience in Times of Change"
              location: "Nye Auditorium"
              code: "ac"
        - time: "2pm – 3pm"
          events:
            - type: "panel"
              content: "Integration in Times of Conflict: Prospects and Challenges of Ukraine’s EU Candidacy "
              location: "Bell Hall"
              code: "dd"
            - type: "panel"
              content: "EU-US Relations: Building Collective Security in a Shifting World"
              location: "Nye Auditorium"
              code: "bc"
        - time: "3:15pm – 3:45pm"
          events:
            - type: "keynote"
              location: "Nye Auditorium"
              speakers:
                - "boone"
        - time: "4:00pm – 5:00pm"
          events:
            - type: "panel"
              content: "Debate: Europe’s Position in a Multipower and Polarized World"
              location: "JFK Forum"
              code: "ba"
        - time: "5:30pm – 6:30pm"
          events:
            - type: "panel"
              content: "What is the Future of Science and Innovation in Europe?"
              location: "JFK Forum"
              code: "ab"
            - type: "panel"
              content: "Challenges to European Democracies: The Rise of Populism and Democratic Backsliding"
              location: "Starr Auditorium"
              code: "db"
    - name: "Saturday, February 10, 2024"
      location: "Harvard Kennedy School of Government (HKS) and TBD"
      slots:
        - time: "8:15am – 9:30am"
          events:
            - type: "other"
              content: "Registration and Breakfast"
        - time: "9:00am - 9:45am"
          events:
            - type: "keynote"
              location: "JFK Forum"
              speakers:
                - "ferreira"
        - time: "10:00am - 11:00am"
          events:
            - type: "panel"
              content: "Challenge and Opportunity: Building Momentum in Migration Policy"
              location: "JFK Forum"
              code: "be"
            - type: "panel"
              content: "Empower Europe: The Road to an Inclusive Energy Transition"
              location: "Starr Auditorium"
              code: "cc"
        - time: "11:00am – 11:30pm"
          events:
            - type: "other"
              content: "Coffee Break"
        - time: "11:30am - 1:00pm"
          events:
            - type: "panel"
              content: "2024, An Election Year: The European Elections and the New Challenges for European Leadership"
              location: "JFK Forum"
              code: "da"
            - type: "panel"
              content: "Ensuring European Competitiveness in the Green Deal Era"
              location: "Starr Auditorium"
              code: "cb"
        - time: "1:00pm – 2:30pm"
          events:
            - type: "other"
              content: "Lunch"
        - time: "2:30pm - 3:00pm"
          events:
            - type: "keynote"
              location: "JFK Forum"
              speakers:
                - "letta"
        - time: "3:15pm - 4:15pm"
          events:
            - type: "panel"
              content: "War and Reconstruction: Crafting a Comprehensive Strategy for Ukraine's Prosperous Future"
              location: "JFK Forum"
              code: "bb"
            - type: "panel"
              content: "AI & (E)U: The Regulatory Road to the Future "
              location: "Starr Auditorium"
              code: "aa"
        - time: "4:15pm – 4:45pm"
          events:
            - type: "other"
              content: "Coffee Break"
        - time: "4:45pm - 5:30pm"
          events:
            - type: "keynote"
              location: "JFK Forum"
              speakers:
                - "sefcovic"
        - time: "5:30pm – 11:30pm"
          events:
            - type: "other"
              content: "Thank You Note"
              location: "JFK Forum"
        - time: "7:00pm - 10:00pm"
          events:
            - type: "other"
              content: "Farewell Reception and Gala"
              location: "TBD"
        
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers + Panels
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: About Us
      url: /about-us
      pageRef: /About Us
      weight: 40
    - name: 2023 Conference
      params:
        rel: external
      url: https://y23.euroconf.eu/
      weight: 50
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      pageRef: /Supporters
      weight: 20
    - name: Privacy
      url: /privacy
      weight: 30
    - name: Terms
      url: /terms
      weight: 30
