baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  schedule:
    - name: "Friday, March 24 2023"
      location: "Harvard Law School"
      slots:
        - time: "12:00 – 12:45"
          events:
            - type: "other"
              content: "Reception, welcome coffee"
              location: "Location TBA"
        - time: "13:00 – 13:30"
          events:
            - type: "keynote"
              content: "Opening Keynote Address"
              location: "Location TBA"
              speakers:
                - "sviatlana"
        - time: "14:00 – 15:00"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "15:30 – 16:30"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "17:00 – 18:00"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "18:30 – 19:30"
          events:
            - type: "keynote"
              content: "Keynote Address"
              location: "Location TBA"
              speakers:
                - "metsola"
    - name: "Saturday, March 25 2023"
      location: "Harvard Kennedy School of Government"
      slots:
        - time: "09:00 - 10:00"
          events:
            - type: "other"
              content: "Welcome breakfast"
              location: "HKS Wintergarden"
        - time: "10:00 - 10:15"
          events:
            - type: "keynote"
              content: "Opening Kenote Address"
              location: "Location TBA"
              speakers:
                - "lambrinidis"
        - time: "10:30 - 11:30"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "12:00 - 13:00"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "13:00 - 14:30"
          events:
            - type: "other"
              content: "Lunch"
              location: "Location TBA"
        - time: "14:30 - 15:30"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "15:30 - 16:00"
          events:
            - type: "other"
              content: "Coffee break"
              location: "Location TBA"
        - time: "16:00 - 17:00"
          events:
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
            - type: "panel"
              content: "Panel discussion TBA"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "17:00 - 17:30"
          events:
            - type: "other"
              content: "Coffee break"
              location: "Location TBA"
        - time: "17:30 - 18:00"
          events:
            - type: "keynote"
              content: "Closing Keynote Address"
              location: "Location TBA"
              speakers:
                - "TBA"
        - time: "20:00 - 23:00"
          events:
            - type: "other"
              content: "Gala Dinner"
              location: "Location TBA"
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Attend
      url: /attend/
      pageRef: attend
      weight: 15
    - name: Speakers
      url: /speakers
      pageRef: speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: schedule
      weight: 30
    - name: Organizers
      url: /organizers
      pageRef: organizers
      weight: 40
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Privacy
      url: /privacy
      weight: 20
    - name: Terms
      url: /terms
      weight: 30
    - name: Sponsors
      url: /sponsors
      weight: 15
