baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  schedule:
    - name: "Thursday, March 23th, 2023"
      location: "Harvard Law School (HLS)"
      slots:
        - time: "6pm - 8pm"
          events:
            - type: "other"
              content: "Conference kick-off: projection of the movie “A House Made of Splinters” (2023 oscar nominee for best documentary). Includes a Q&A with the film crew."
              location: "Langdell 225N (HLS)"
    - name: "Friday, March 24th, 2023"
      location: "Harvard Law School (HLS) and Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "11:30am – 12:30pm"
          events:
            - type: "other"
              content: "Registration and Welcome Lunch"
              location: "Room TBD (HLS)"
        - time: "12:45pm – 1:45pm"
          events:
            - type: "panel"
              content: "Democratic Backsliding in the EU and the US"
              location: "Austin 100 (HLS)"
              speakers:
                - "letta"
                - "klarman"
            - type: "panel"
              content: "Role of Courts in Civil Rights Adjudication Among Diverse States"
              location: "Austin 111 (HLS)"
              speakers:
                - "valasidis"
                - "kornezov"
                - "sharpston"
        - time: "2pm – 3pm"
          events:
            - type: "panel"
              content: "Negotiating Brexit: a Workshop with Michel Barnier"
              location: "Austin 100 (HLS)"
              speakers:
                - "barnier"
            - type: "panel"
              content: "Energy Security in Today’s World"
              location: "Austin 111 (HLS)"
              speakers:
                - "sdoukou"
                - "lassen"
                - "kosciusko-morizet"                
              moderator: "lee"
        - time: "3pm – 4pm"
          events:
            - type: "other"
              content: "Transfer to HKS"
         
        - time: "4pm – 5pm"
          events:
            - type: "keynote"
              content: "Europe’s Struggle for Relevance, Unity and Value: A Conversation with Roberta Metsola and Sviatlana Tsikhanouskaya"
              location: "JFK Forum (HKS)"
              speakers:
                - "metsola"
                - "tsikhanouskaya"
                
        - time: "5:15pm – 6:15pm"
          events:
            - type: "panel"
              content: "Stronger Together: A Revitalized Transatlantic Relationship"
              location: "L-140 (HKS)"
              speakers:
                - "etienne"
                - "braze"
                - "wieslander"
                - "debski"
            - type: "panel"
              content: "The State and Future of EU Enlargement : the Balkans as the New Frontier?"
              location: "Wexner 436 (HKS)"
              speakers:
                - "mathernova"
                - "duric"
                - "popov"
                - "adam"
              moderator: "papoulias"
              
        - time: "6:45pm – 9pm"
          events:
            - type: "other"
              content: "Reception"
              location: "Harvard Museum of Natural History"
    - name: "Saturday, March 25 2023"
      location: "Harvard Kennedy School of Government"
      slots:
        - time: "8:30am - 9:15am"
          events:
            - type: "other"
              content: "Breakfast"
              location: "Wintergarden (HKS)"
             
        - time: "9:30am - 9:45am"
          events:
            - type: "keynote"
              content: "Opening Address"
              location: "JFK Forum (HKS)"
              speakers:
                - "lambrinidis"
        - time: "9:45am - 10:30am"
          events:
            - type: "keynote"
              content: "Live from Kyiv: a conversation with ex-Prime Minister of Ukraine Oleksiy Honcharuk"
              location: "JFK Forum (HKS)"
              speakers:
                - "honcharuk"
        - time: "10:45am - 11:45am"
          events:
            - type: "panel"
              content: "One year of War in Ukraine and its impact on Europe (and beyond)"
              location: "JFK Forum (HKS)"
              speakers:
                - "letta"
                - "kyslytsya"
                - "schwarzer"
            - type: "panel"
              content: "The Digital Markets Act"
              location: "Wexner W-436 (HKS)"
              speakers:
                - "zuber"
                - "katona"
                - "kimmelman"
                - "oeyen"
            - type: "panel"
              content: "Rising Strong: Building Resilient Supply Chains in Europe"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "dagoumas"
                - "lacoue"
        - time: "12pm - 1pm"
          events:
            - type: "panel"
              content: "The European Green Deal and the Inflation Reduction Act: How Europe and the United States are Tackling the Climate Crisis"
              location: "JFK Forum (HKS)"
              speakers:
                - "etienne"
                - "patel"
                - "sivaram"
              moderator: "Catherine Wolfram"
            - type: "panel"
              content: "EU - Africa: Assessing the Relationship in the Context of War in Ukraine"
              location: "Wexner W-436 (HKS)"
              speakers:
                - "chahed"
                - "kadayifci-orellana"
            - type: "panel"
              content: "The role of Europe in the US-China rivalry"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "larres"
                - "berzina-cerenkova"
                - "schwarzer"
        - time: "1pm - 2:15pm"
          events:
            - type: "other"
              content: "Lunch"
              location: "Wintergarden (HKS)"
        - time: "2:15pm - 3:15pm"
          events:
            - type: "panel"
              content: "The Future of the EU’s Political Union"
              location: "JFK Forum (HKS)"
              speakers:
                - "verhofstadt"
              moderator: "Daniela Schwarzer"
            - type: "panel"
              content: "Rivals or Partners? The future of the EU-UK relationship"
              location: "Littauer L-140 (HKS)"
              speakers:
                - "barnier"
            - type: "panel"
              content: "The Final Frontier: Future of Space Policy in Europe and Beyond"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "oesterschlink"
                - "espinasse"
        - time: "3:15pm - 3:45pm"
          events:
            - type: "other"
              content: "Coffee Break"
              location: "Wintergarden (HKS)"
              
        - time: "3:45pm - 4:45pm"
          events:
            - type: "panel"
              content: "What’s Next for Investment in Europe?"
              location: "JFK Forum (HKS)"
              speakers:
                - "dias"
                - "lucas"
            - type: "panel"
              content: "The World’s largest Construction Site: Rebuilding Post-war in Ukraine"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "koszarny"
                - "gaudin"
            - type: "panel"
              content: "Freedom of Speech and the Digital Services Act"
              location: "Wexner W-436 (HKS)"
              speakers:
                - "mchangama"
                - "havlik"
                - "shear"
                - "wezenbeek"
              moderator: "Kate Klonick"
        - time: "5pm - 6pm"
          events:
            - type: "panel"
              content: "Addressing Europe’s Long-Term Migration Strategy"
              location: "JFK Forum (HKS)"
              speakers:
                - "brkljac"
                - "kayacik"
                - "maniatis"
            - type: "panel"
              content: "Finding Europe: a continent’s renewed quest for identity and values"
              location: "JFK Forum (HKS)"
              speakers:
                - "buldioski"
                - "novosad"
                - "prevedourou"
            - type: "panel"
              content: "Addressing Europe’s Long-Term Migration Strategy"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "brkljac"
            

        - time: "6:15pm - 6:30pm"
          events:
            - type: "keynote"
              content: "Closing Address"
              location: "JFK Forum (HKS)"
              speakers:
                - "schwarzer"


menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Attend
      url: /attend/
      pageRef: attend
      weight: 15
    - name: Speakers
      url: /speakers
      pageRef: speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: schedule
      weight: 30
    - name: Organizers
      url: /organizers
      pageRef: organizers
      weight: 40
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Privacy
      url: /privacy
      weight: 20
    - name: Terms
      url: /terms
      weight: 30
    - name: Sponsors
      url: /sponsors
      weight: 15
