baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, February 9, 2024"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "11:15am – 12:00pm"
          events:
            - type: "other"
              content: "Registration and Welcome Lunch"
        - time: "12:00pm – 12:45pm"
          events:
            - type: "keynote"
              content: "A Pivotal Year: What’s at Stake in 2024 for Europe, America, and the World"
              location: "Nye Auditorium"
              keynote: a
        - time: "1:00pm – 2:00pm"
          events:
            - type: "panel"
              content: "Empower Europe: The Road to an Inclusive Energy Transition"
              location: "Nye Auditorium"
              moderator: "macomber"
              code: "cc"
            - type: "panel"
              content: "Challenges to European Democracies: The Rise of Populism and Democratic Backsliding"
              location: "Allison Room"
              moderator: "agathos"
              code: "db"
            - type: "workshop"
              content: "Workshop: A Discussion with Bojan Marichikj"
              location: "Littauer Deland"
        - time: "2:15pm – 3:15pm"
          events:
            - type: "panel"
              content: "Integration in Times of Conflict: Prospects and Challenges of Ukraine’s EU Candidacy"
              location: "Nye Auditorium"
              moderator: "bergmann"
              code: "dd"
            - type: "panel"
              content: "Building Global Coalitions on Feminism, LGBTQ Rights, and Minorities Representation"
              location: "Allison Room"
              moderator: "ayee"
              code: "dc"
            - type: "workshop"
              content: "Workshop: A Discussion with Péter Szijjártó"
              location: "TBD"
        - time: "3:15pm – 4:00pm"
          events:
            - type: "other"
              content: "Coffee Break + Moving to Forum"
            - type: "workshop"
              content: "Workshop: A Discussion with Sebastian Burduja"
              location: "Littauer Deland"
        - time: "4:00pm – 5:00pm"
          events:
            - type: "panel"
              content: "Europe’s Position in a Multipower and Polarized World"
              location: "JFK Jr. Forum"
              moderator: "donfried"
              code: "ba"
        - time: "5:30pm – 6:30pm"
          events:
            - type: "panel"
              content: "What is the Future of Science and Innovation in Europe?"
              location: "JFK Jr. Forum"
              code: "ab"
              moderator: "chalupowski"
            - type: "panel"
              content: "Navigating New Normals: Europe’s Economic Resilience in Times of Change"
              location: "Starr Auditorium"
              code: "ac"
              moderator: "ivashina"
            - type: "workshop"
              content: "Workshop: Negotiating Climate Agreements"
              location: "TBD"
    - name: "Saturday, February 10, 2024"
      location: "Harvard Kennedy School of Government (HKS) and TBD"
      slots:
        - time: "8:15am – 9:00am"
          events:
            - type: "other"
              content: "Registration and Breakfast"
        - time: "9:00am - 9:45am"
          events:
            - type: "keynote"
              content: "Cohesion: A Pre-Condition for Unity"
              location: "JFK Jr. Forum"
              keynote: c
        - time: "10:00am - 11:00am"
          events:
            - type: "panel"
              content: "War and Reconstruction: Crafting a Comprehensive Strategy for Ukraine's Prosperous Future"
              location: "JFK Jr. Forum"
              code: "bb"
              moderator: "plokhii"
            - type: "panel"
              content: "Challenge and Opportunity: Building Momentum in Migration Policy"
              location: "Starr Auditorium"
              moderator: "papoulias"
              code: "be"
            - type: "workshop"
              content: "Workshop: A Discussion with Gabriele Mazzini"
              location: "TBD"
        - time: "11:00am – 11:30pm"
          events:
            - type: "other"
              content: "Coffee Break"
        - time: "11:30am - 1:00pm"
          events:
            - type: "panel"
              content: "2024, An Election Year: The European Elections and the New Challenges for European Leadership"
              location: "JFK Jr. Forum"
              code: "da"
              moderator: "agathos"
            - type: "panel"
              content: "Ensuring European Competitiveness in the Green Deal Era"
              location: "Starr Auditorium"
              code: "cb"
              moderator: "vinhas-de-souza"
            - type: "workshop"
              content: "Workshop: A Discussion with Dimitris Kairidis"
              location: "Littauer Deland"
        - time: "1:00pm – 2:15pm"
          events:
            - type: "other"
              content: "Lunch"
        - time: "2:15pm - 3:00pm"
          events:
            - type: "keynote"
              location: "JFK Jr. Forum"
              keynote: d
              moderator: "schwarzer"
        - time: "3:15pm - 4:15pm"
          events:
            - type: "panel"
              content: "EU-US Relations: Building Collective Security in a Shifting World"
              location: "JFK Jr. Forum"
              moderator: "shapiro"
              code: "bc"
            - type: "panel"
              content: "AI & (E)U: The Regulatory Road to the Future"
              location: "Starr Auditorium"
              moderator: "zanfir"
              code: "aa"
        - time: "4:15pm – 4:45pm"
          events:
            - type: "other"
              content: "Coffee Break"
        - time: "4:45pm - 5:30pm"
          events:
            - type: "keynote"
              content: "The European Green Deal: Time for a New Deal?"
              location: "JFK Jr. Forum"
              keynote: e
              speaker: "sefcovic"
        - time: "5:30pm – 5:45pm"
          events:
            - type: "other"
              content: "Farewell Address"
              location: "JFK Jr. Forum"
        - time: "8:00pm - 11:00pm"
          events:
            - type: "other"
              content: "Farewell Reception and Gala"
              location: "Harvard Faculty Club"
        
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
