baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, February 9, 2024"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "11:15am – 12:00pm"
          events:
            - type: "other"
              content: "Registration and Welcome Lunch"
        - time: "12:00pm – 12:45pm"
          events:
            - type: "keynote"
              location: "Nye Auditorium"
              speakers:
                - "gentiloni"
        - time: "12:50pm – 1:50pm"
          events:
            - type: "panel"
              content: "Building Global Coalitions on Feminism, LGBTQ Rights, and Minorities Representation"
              location: "Bell Hall"
              code: "dc"
            - type: "panel"
              content: "Navigating New Normals: Europe’s Economic Resilience in Times of Change"
              location: "Nye Auditorium"
              code: "ac"
        - time: "2pm – 3pm"
          events:
            - type: "panel"
              content: "Integration in Times of Conflict: Prospects and Challenges of Ukraine’s EU Candidacy "
              location: "Bell Hall"
              code: "dd"
            - type: "panel"
              content: "EU-US Relations: Building Collective Security in a Shifting World"
              location: "Nye Auditorium"
              code: "bc"
        - time: "3:15pm – 3:45pm"
          events:
            - type: "keynote"
              location: "Nye Auditorium"
              speakers:
                - "boone"
        - time: "4pm – 5pm"
          events:
            - type: "panel"
              content: "Debate: Europe’s Position in a Multipower and Polarized World"
              location: "JFK Forum"
              code: "ba"
        - time: "5:30pm – 6:30pm"
          events:
            - type: "panel"
              content: "What is the Future of Science and Innovation in Europe?"
              location: "JFK Forum"
              code: "ab"
            - type: "panel"
              content: "Challenges to European Democracies: The Rise of Populism and Democratic Backsliding"
              location: "Starr Auditorium"
              code: "db"
    - name: "Saturday, February 10, 2024"
      location: "Harvard Kennedy School of Government (HKS) and TBD"
      slots:
        - time: "9:00am - 9:45pm"
          events:
            - type: "panel"
              content: "Challenge and Opportunity: Building Momentum in Migration Policy"
              location: "JFK Forum"
              code: "be"
        - time: "7:00pm - 10:00pm"
          events:
            - type: "other"
              content: "Reception and Gala"
              location: "TBD"
        
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers + Panels
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: About Us
      url: /about-us
      pageRef: /About Us
      weight: 40
    - name: 2023 Conference
      params:
        rel: external
      url: https://y23.euroconf.eu/
      weight: 50
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      pageRef: /Supporters
      weight: 20
    - name: Privacy
      url: /privacy
      weight: 30
    - name: Terms
      url: /terms
      weight: 30
