baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, February 9, 2024"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "11:15am – 12:00pm"
          events:
            - type: "other"
              content: "Registration and Welcome Lunch"
        - time: "12:00pm – 12:45pm"
          events:
            - type: "keynote"
              location: "Nye Auditorium"
              speakers:
                - "gentiloni"
        - time: "12:50pm – 1:50pm"
          events:
            - type: "panel"
              content: "Building Global Coalitions on Feminism, LGBTQ Rights, and Minorities Representation"
              location: "Bell Hall"
              code: dc
            - type: "panel"
              content: "Navigating New Normals: Europe’s Economic Resilience in Times of Change"
              location: "Nye Auditorium"
              code: ac
        - time: "2pm – 3pm"
          events:
            - type: "panel"
              content: "Negotiating Brexit: a Discussion with Michel Barnier"
              location: "Austin 100 (HLS)"
              speakers:
                - "barnier"
              moderator: "Hugh O'Doherty"
            - type: "panel"
              content: "Energy Security in Today’s World"
              location: "Austin 111 (HLS)"
              speakers:
                - "sdoukou"
                - "lassen"
                - "kosciusko-morizet"
                - "scharioth"
              moderator: "lee"
        - time: "3pm – 4pm"
          events:
            - type: "other"
              content: "Transfer to HKS"
         
        - time: "4pm – 5pm"
          events:
            - type: "keynote"
              content: "Europe’s Struggle for Relevance, Unity and Value: A Conversation with Roberta Metsola and Sviatlana Tsikhanouskaya"
              location: "JFK Forum (HKS)"
              speakers:
                - "metsola"
                - "tsikhanouskaya"
              moderator: "Grzegorz Ekiert"
                
        - time: "5:15pm – 6:15pm"
          events:
            - type: "panel"
              content: "Stronger Together: A Revitalized Transatlantic Relationship"
              location: "W436 (HKS)"
              speakers:
                - "etienne"
                - "braze"
                - "wieslander"
                - "debski"
              moderator: "Stephen Walt"
            - type: "panel"
              content: "The State and Future of EU Enlargement : the Balkans as the New Frontier?"
              location: "Starr Auditorium (HKS)"
              speakers:
                - "mathernova"
                - "duric"
                - "popov"
                - "adam"
              moderator: "papoulias"
    - name: "Saturday, February 10, 2024"
      location: "Harvard Kennedy School of Government (HKS) and TBD"
      slots:
        - time: "9:00am - 6:00pm"
          events:
            - type: "other"
              content: "Conference Events and Panels"
              location: "HKS"  
        - time: "7:00pm - 10:00pm"
          events:
            - type: "other"
              content: "Reception and Gala"
              location: "TBD"
        
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers + Panels
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: About Us
      url: /about-us
      pageRef: /About Us
      weight: 40
    - name: 2023 Conference
      params:
        rel: external
      url: https://y23.euroconf.eu/
      weight: 50
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      pageRef: /Supporters
      weight: 20
    - name: Privacy
      url: /privacy
      weight: 30
    - name: Terms
      url: /terms
      weight: 30
