baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  schedule:
    - name: "Friday, March 24th, 2023"
      location: "Center for European Studies (CES) and Harvard Law School (HLS)"
      slots:
        - time: "11h30 – 12h15"
          events:
            - type: "other"
              content: "Reception, Welcome coffee"
              location: "Adolphus Busch Hall (CES)"
        - time: "12h30 – 13h00"
          events:
            - type: "keynote"
              content: "Opening Keynote Address"
              location: "Yenching Auditorium (CES)"
              speakers:
                - "tsikhanouskaya"
        - time: "13h30 – 14h30"
          events:
            - type: "panel"
              content: "Stronger together: A revitalized Transatlantic relationship"
              location: "Austin 100 (HLS)"
              speakers:
                - "etienne"
                - "braze"
                - "wieslander"
              moderator: "Natalie Colbert"
            - type: "panel"
              content: "Role of courts in civil rights adjudication among diverse states"
              location: "Austin 111 (HLS)"
              speakers:
                - "valasidis"
                - "bobek"
                - "sharpston"
              moderator: "TBA"
        - time: "14h45 – 15h45"
          events:
            - type: "panel"
              content: "The state and future of EU enlargement: the Balkans as the new frontier?"
              location: "Austin 111 (HLS)"
              speakers:
                - "mathernova"
                - "duric"
                - "popov"
                - "adam"
              moderator: "Elaine Papoulias"
            - type: "panel"
              content: "The European Green Deal vs. the Inflation Reduction Act"
              location: "Austin 100 (HLS)"
              speakers:
                - "etienne"
                - "patel"
                - "sivaram"
              moderator: "TBA"
        - time: "15h45 – 16h15"
          events:
            - type: "other"
              content: "Coffee Break"
              location: "TBA"
        - time: "16h15 – 17h15"
          events:
            - type: "panel"
              content: "Democratic backsliding in the EU and the US"
              location: "Ames Courtroom (HLS)"
              speakers:
                - "klarman"
                - "adam"
                - "mecacci"
                - "tsikhanouskaya"
              moderator: "Vincent Pons"
            - type: "panel"
              content: "Europe's Energy Crunch: Redefining the future of the EU's energy security model"
              location: "Austin 100 (HLS)"
              speakers:
                - "sdoukou"
                - "lassen"
              moderator: "TBA"
        - time: "17h30 – 18h00"
          events:
            - type: "keynote"
              content: "Keynote Address"
              location: "Ames Courtroom (HLS)"
              speakers:
                - "metsola"
        - time: "18h30 – 21h00"
          events:
            - type: "other"
              content: "Official Reception"
              location: "Harvard Museum of Natural History"
    - name: "Saturday, March 25 2023"
      location: "Harvard Kennedy School of Government"
      slots:
        - time: "09:00 - 10:00"
          events:
            - type: "other"
              content: "Breakfast"
              location: "Wintergarden"
            - type: "other"
              content: "VIP Breakfast"
              location: "Malkin Penthouse"
        - time: "10:00 - 10:15"
          events:
            - type: "keynote"
              content: "Opening Keynote Address"
              location: "JFK Forum"
              speakers:
                - "lambrinidis"
        - time: "10:30 - 11:30"
          events:
            - type: "panel"
              content: "One year of War in Ukraine and its impact on Europe (and beyond)"
              location: "JFK Forum"
              speakers:
                - "letta"
                - "honcharuk"
                - "kyslytsya"
              moderator: "Eric Rosenbach"
            - type: "panel"
              content: "The Digital Market Act"
              location: "TBA"
              speakers:
                - "zuber"
                - "sallet"
              moderator: "TBA"
            - type: "panel"
              content: "Stagnating Growth, Inflation, Rising Energy Prices: Impact for Businesses"
              location: "TBA"
              speakers:
                - "dagoumas"
                - "lacoue"
                - "panucci"
              moderator: "TBA"
        - time: "12:00 - 13:00"
          events:
            - type: "panel"
              content: "What’s Next for Investment in Europe?"
              location: "JFK Forum"
              speakers:
                - "dias"
                - "kosusko-morizet"
                - "lucas"
              moderator: "TBA"
            - type: "panel"
              content: "Reassessing policy towards Africa in light of the war in Ukraine & Cop 27"
              location: "Wexner W-436"
              speakers:
                - "chahed"
              moderator: "Tarek Masoud"
            - type: "panel"
              content: "Europe & Pacific (The role of Europe in the US-China rivalry)"
              location: "Starr Auditorium"
              speakers:
                - "larres"
                - "berzina-cerenkova"
              moderator: "Graham Allison"
        - time: "13:00 - 14:30"
          events:
            - type: "other"
              content: "Lunch"
              location: "Wintergarden and Malkin Penthouse"
        - time: "14:30 - 15:30"
          events:
            - type: "panel"
              content: "Future of the European Union"
              location: "JFK Forum"
              speakers:
                - "verhofstadt"
              moderator: "Daniela Schwarzer"
            - type: "panel"
              content: "Regulating Big Tech"
              location: "Littauer L-140"
              speakers:
                - "fiske"
                - "kimmelman"
                - "haigh"
                - "bradford"
              moderator: "John Haigh"
            - type: "panel"
              content: "Long-term migration strategy in the EU"
              location: "Starr Auditorium"
        - time: "15:30 - 16:00"
          events:
            - type: "other"
              content: "Coffee Break"
              location: "Wintergarden"
        - time: "16:00 - 17:00"
          events:
            - type: "panel"
              content: "Rebuilding Ukraine"
              location: "Starr Auditorium"
              speakers:
                - "kachur"
                - "gaudin"
                - "TBA"
              moderator: "TBA"
            - type: "panel"
              content: "EU/UK relationship"
              location: "JFK Forum"
              speakers:
                - "barnier"
              moderator: "TBA"
            - type: "panel"
              content: "Freedom of Speech and the Digital Services Act"
              location: "Wexner W-436"
              speakers:
                - "shear"
                - "mchangama"
                - "klonick"
              moderator: "TBA"
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Attend
      url: /attend/
      pageRef: attend
      weight: 15
    - name: Speakers
      url: /speakers
      pageRef: speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: schedule
      weight: 30
    - name: Organizers
      url: /organizers
      pageRef: organizers
      weight: 40
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Privacy
      url: /privacy
      weight: 20
    - name: Terms
      url: /terms
      weight: 30
    - name: Sponsors
      url: /sponsors
      weight: 15
