baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, January 31, 2025"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "1:30pm – 2:00pm"
          events:
            - type: "other"
              content: "Welcome Coffee"
        - time: "2:00pm – 3:00pm"
          events:
            - type: "keynote"
              content: "Opening Remarks and Keynote"
              location: "Nye Auditorium"
              keynote: a
        - time: "3:00pm – 3:30pm"
          events:
            - type: "other"
              content: "Break"
        - time: "3:30pm – 4:45pm"
          events:
            - type: "panel"
              content: "Europe’s Role in Middle East Peace"
              location: "Nye Auditorium"
              code: "c"
            - type: "panel"
              content: "Being European"
              location: "TBD"
              code: "b"
            - type: "workshop"
              content: "Workshop"
        - time: "4:45pm – 5:15pm"
          events:
            - type: "other"
              content: "Break"
        - time: "5:15pm – 6:00pm"
          events:
            - type: "keynote"
              content: "Keynote or High Level Dialogue"
              location: "JFK Jr. Forum"
              keynote: "b"
    - name: "Saturday, February 1, 2025"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "8:00am – 9:00am"
          events:
            - type: "other"
              content: "Breakfast"
        - time: "9:00am - 9:45am"
          events:
            - type: "keynote"
              content: "Keynote"
              location: "Starr Auditorium"
              keynote: c
            - type: "other"
              content: "High-Level Dialogue"
              location: "JFK Jr. Forum"
        - time: "9:45am – 10:15am"
          events:
            - type: "other"
              content: "Break"
        - time: "10:15am - 11:30am"
          events:
            - type: "panel"
              content: "Fortifying Europe's Frontlines"
              location: "JFK Jr. Forum"
              code: "h"
            - type: "panel"
              content: "Boosting Europe's Economy"
              location: "Starr Auditorium"
              code: "a"
            - type: "workshop"
              content: "Workshop"
              location: "TBD"
        - time: "11:30am – 12:00pm"
          events:
            - type: "other"
              content: "Coffee Break"
        - time: "12:00pm - 1:15pm"
          events:
            - type: "panel"
              content: "Europe's Global Diplomacy"
              location: "JFK Jr. Forum"
              code: "g"
            - type: "panel"
              content: "Brain Drain and Emerging Tech"
              location: "Starr Auditorium"
              code: "j"
            - type: "workshop"
              content: "Workshop"
        - time: "1:15pm – 2:15pm"
          events:
            - type: "other"
              content: "Lunch"
              location: "Wexner Commons"
        - time: "2:15pm - 3:30pm"
          events:
            - type: "panel"
              content: "Europe's Energy Trifecta"
              location: "JFK Jr. Forum"
              code: "f"
            - type: "panel"
              content: "The Union under Strain"
              location: "Starr Auditorium"
              code: "d"
            - type: "workshop"
              content: "Workshop"
              location: "JFK Jr. Forum"
        - time: "3:30pm – 4:00pm"
          events:
            - type: "other"
              content: "Break"
        - time: "4:00pm - 5:15pm"
          events:
            - type: "panel"
              content: "Migration"
              location: "JFK Jr. Forum"
              code: "e"
            - type: "panel"
              content: "Pretense or Promise"
              location: "Starr Auditorium"
              code: "i"
            - type: "workshop"
              content: "Workshop"
              location: "JFK Jr. Forum"
        - time: "5:15pm – 5:45pm"
          events:
            - type: "other"
              content: "Break"
        - time: "5:45pm – 6:45pm"
          events:
            - type: "keynote"
              content: "Keynote and Farewell Address"
              location: "JFK Jr. Forum"
        - time: "8:00pm - 11:30pm"
          events:
            - type: "other"
              content: "Closing Gala"
              location: "Harvard Art Museum"
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers + Panels
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: Gala
      url: /gala
      pageRef: /Gala
      weight: 35
#    - name: Info
#      url: /info
#      pageRef: /info
#      weight: 40
#    - name: About Us
#      url: /about-us
#      pageRef: /About Us
#      weight: 50
    - name: Past Conferences
      weight: 60
    - name: 2024 Conference
      parent: Past Conferences
      rel: external
      url: https://y24.euroconf.eu/
      weight: 10
    - name: 2023 Conference
      parent: Past Conferences
      rel: external
      url: https://y23.euroconf.eu/
      weight: 20
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      weight: 15
    - name: Privacy
      url: /privacy
      weight: 20
    - name: Terms
      url: /terms
      weight: 30
