baseURL: http://hugo-quickstart-template.netlify.com
languageCode: en-us
title: European Conference
theme: europeanconference
staticDir:
  - static
markup:
  goldmark:
    renderer:
      unsafe: true
security:
  exec:
    allow:
    - '^go$'
    - '^npx$'
    - '^postcss$'
    - '^babel$'
params:
  schedule:
    - name: "Friday, February 9, 2024"
      location: "Harvard Kennedy School of Government (HKS)"
      slots:
        - time: "12:00pm – 6:30pm"
          events:
            - type: "other"
              content: "Conference Events and Panels"
              location: "HKS"
    - name: "Saturday, February 10, 2024"
      location: "Harvard Kennedy School of Government (HKS) and Harvard Museum of Natural History"
      slots:
        - time: "9:00am - 6:00pm"
          events:
            - type: "other"
              content: "Conference Events and Panels"
              location: "HKS"  
        - time: "7:00pm - 10:00pm"
          events:
            - type: "other"
              content: "Reception and Gala"
              location: "Harvard Museum of Natural History"
        
menu:
  main:
    - name: Home
      url: /
      pageRef: /
      weight: 10
    - name: Speakers
      url: /speakers
      pageRef: /Speakers
      weight: 20
    - name: Schedule
      url: /schedule
      pageRef: /Schedule
      weight: 30
    - name: About Us
      url: /about-us
      pageRef: /About Us
      weight: 40
    - name: 2023 Conference
      params:
        rel: external
      url: https://y23.euroconf.eu/
      weight: 50
  footer:
    - name: Contact
      url: /contact
      weight: 10
    - name: Supporters
      url: /supporters
      pageRef: /Supporters
      weight: 20
    - name: Privacy
      url: /privacy
      weight: 30
    - name: Terms
      url: /terms
      weight: 30
